name: Build and Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-gcc-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prereq
      run: sudo apt-get install gobject-introspection gir1.2-glib-2.0 libgirepository1.0-dev gcc gfortran pkg-config libglib2.0-dev libgmp3-dev libmpfr-dev libgsl0-dev libfftw3-dev libopenblas-dev libflint-arb-dev libcfitsio-dev libnlopt-dev libhdf5-dev gtk-doc-tools texlive texlive-bibtex-extra texlive-science texlive-publishers tex4ht perl libxml-libxml-perl
    - name: Autogen
      run: NOCONFIGURE=yes ./autogen.sh
    - name: configure
      run: ./configure --enable-gtk-doc --enable-man
    - name: make
      run: make -j8
    - name: make check
      run: make check -j8
    - name: make dist
      run: make dist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: numcosmo-*.tar.gz

  coveralls-gcc-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prereq
      run: sudo apt-get install gobject-introspection gir1.2-glib-2.0 libgirepository1.0-dev gcc gfortran pkg-config libglib2.0-dev libgmp3-dev libmpfr-dev libgsl0-dev libfftw3-dev libopenblas-dev libflint-arb-dev libcfitsio-dev libnlopt-dev libhdf5-dev
    - name: Autogen
      run: NOCONFIGURE=yes ./autogen.sh
    - name: configure
      run: ./configure 'CFLAGS=-Wall -g -O0' 'FCFLAGS=-O0 -Wall' --enable-maintainer-mode --disable-gtk-doc --prefix=/usr --enable-code-coverage
    - name: make
      run: make -j8
    - name: make check
      run: make check -j8
    - name: Run coveralls
      run: |
        sudo pip3 install cpp-coveralls python-coveralls
        cpp-coveralls --gcov-options '\-lp' -i tests -r tests
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build-gcc-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install prereq
      run: brew install autoconf automake libtool gobject-introspection gsl gmp mpfr fftw cfitsio nlopt
    - name: Autogen
      run: NOCONFIGURE=yes ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j8
    - name: make check
      run: make check -j8

